### ISSUE TITLE
Should the SAA always inform the IETF at level 1 (cooling off period)?

### ISSUE THREAD

**Issue by elear** [ietf/saa#11]
To avoid unnecessary embarrassment, might it make sense to offer the individual the option of not having that note sent, with the caveat that continued violation can lead to a posting rights suspension?

**Comment by mnot** [comment]
I question whether we should be optimising to avoid embarrassment of people who have behaved unprofessionally as a first order concern; see #14.

**Comment by elear** [comment]
Let's merge this with #14.
