### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by bobhinden** [ietf/saa#6]
Not sure I am doing this correctly in github, but regarding:

> Personal attacks
> Personal attacks include attacking people for their opinions, beliefs, or ideas rather than criticizing the opinions, beliefs, and ideas themselves. Personal attacks also include name-calling and insulting, demeaning, or belittling others.

I think it is good this is clear it is about attacking "people".     For example, someone saying that Bob is stupid.   

I think two things are  missing from the IETF-SSA.  These are:

Criticism of the actions of the IETF leadership bodies should be given a lot of latitude.  Not to the point where it falls into personal attacks on people (that is, individuals) in the leadership body, but it should be fine to criticize the actions of a leadership body.  Other wise, the SSA will be perceived as being used to censor the IETF community to protect the leadership.

The other is that with the exception of the IETF Chair, members of the SAA team should not hold IETF leadership positions.   I understand the issues of getting people to do this job, but there is too much inherent conflict of interest otherwise.

**Comment by coopdanger** [comment]
> Criticism of the actions of the IETF leadership bodies should be given a lot of latitude. Not to the point where it falls into personal attacks on people (that is, individuals) in the leadership body, but it should be fine to criticize the actions of a leadership body. Other wise, the SSA will be perceived as being used to censor the IETF community to protect the leadership.

I don't understand the implications of this for the SOP. IMO either we expect everyone to remain professional regardless of the subject matter, or we don't. The latter constitutes a double standard and that's not something I'm prepared to be associated with.

> The other is that with the exception of the IETF Chair, members of the SAA team should not hold IETF leadership positions. I understand the issues of getting people to do this job, but there is too much inherent conflict of interest otherwise.

This seems like fodder for an RFC 3005 update.

**Comment by dhruvdhody** [comment]
We have noted the last point in our list of possible update ideas for RFC 3005.
